import { runGameEngineTests } from "./GameEngineTest";
import { runRulesTests } from "./RulesTest";
import { runRangeTests } from "./RangeTest";
import { runPathfindingTests } from "./PathfindingTest";
import { runFiveFootStepTests } from "./FiveFootStepTest";
import { runStabilizationTests } from "./StabilizationTest";
import { runSavingThrowTests } from "./SavingThrowTest";
import { runConditionTests } from "./ConditionTest";
import { runDisabledTests } from "./DisabledTest";
import { runHpTransitionTests } from "./HpTransitionTest";
import { runCoupDeGraceTests } from "./CoupDeGraceTest";
import { runCoupDeGraceIntegrationTests } from "./CoupDeGraceIntegrationTest";
import { runCombatResolutionTests } from "./CombatResolutionTest";
import { runSocialRulesTests } from "./SocialRulesTest";
import { runSocialCombatIntegrationTests } from "./SocialCombatIntegrationTest";
import { runAiTests } from "./AiTest";
import { runCombatMovementTests } from "./CombatMovementTest";
import { runWithdrawTests } from "./WithdrawTest";
import { runCombatMovementIntegrationTests } from "./CombatMovementIntegrationTest";
import { runEncounterInitiativeTests } from "./EncounterInitiativeTest";
import { runGameCoreServerIntegrationTests } from "./GameCoreServerIntegrationTest";
import { runEncounterActionsTests } from "./EncounterActionsTest";

runGameEngineTests();
runRulesTests();
runRangeTests();
runPathfindingTests();
runFiveFootStepTests();
runStabilizationTests();
runSavingThrowTests();
runConditionTests();
runDisabledTests();
runHpTransitionTests();
runCoupDeGraceTests();
runCoupDeGraceIntegrationTests();
runCombatResolutionTests();
runSocialRulesTests();
runSocialCombatIntegrationTests();
runAiTests();
runCombatMovementTests();
runWithdrawTests();
runCombatMovementIntegrationTests();
runEncounterInitiativeTests();
runEncounterActionsTests();
runGameCoreServerIntegrationTests();
